### ISSUE TITLE
Make API endpoints configurable?

### ISSUE THREAD

**Issue by adamlc** [MarcoGos/kleenex_nl_pollenradar#1]
It looks like the .co.uk API is exactly the same structure as the nl one. I wondered if it was possible to update this project to make the endpoints configurable so us UK users can use it too?

**Comment by MarcoGos** [comment]
Hi @adamlc, I created a new pollen integration called "Kleenex Pollenradar" which should help you out. Can you try to install the new integration via HACS as you did the "Kleenex NL Pollenradar"? You need the following url: "https://github.com/MarcoGos/kleenex_pollenradar". See also the readme on this url.

**Comment by adamlc** [comment]
@MarcoGos this is fantastic thanks! Its working perfectly for me, I did fork this repo, but the config screen you have is much better. 

Thank you :)
